namespace Syno.TinyTorrent.Subtitles;

internal sealed partial class SubDL
{
    private static readonly IReadOnlyDictionary<string, string> LanguageCodes =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["sq"] = "SQ",
            ["ar"] = "AR",
            ["hy"] = "HY",
            ["az"] = "AZ",
            ["eu"] = "EU",
            ["be"] = "BE",
            ["bn"] = "BN",
            ["bs"] = "BS",
            ["bg"] = "BG",
            ["my"] = "MY",
            ["ca"] = "CA",
            ["zh-Hans"] = "ZH",
            ["zh-Hant"] = "ZH_BG",
            ["hr"] = "HR",
            ["cs"] = "CS",
            ["da"] = "DA",
            ["nl"] = "NL",
            ["en"] = "EN",
            ["eo"] = "EO",
            ["et"] = "ET",
            ["fa"] = "FA",
            ["fi"] = "FI",
            ["fr"] = "FR",
            ["fr-CA"] = "FR_CA",
            ["gl"] = "GL",
            ["ka"] = "KA",
            ["de"] = "DE",
            ["el"] = "EL",
            ["kl"] = "KL",
            ["he"] = "HE",
            ["hi"] = "HI",
            ["hu"] = "HU",
            ["is"] = "IS",
            ["id"] = "ID",
            ["ga"] = "GA",
            ["it"] = "IT",
            ["ja"] = "JA",
            ["jv"] = "JV,JW",
            ["kn"] = "KN",
            ["kk"] = "KK",
            ["km"] = "KM",
            ["ko"] = "KO",
            ["ku"] = "KU",
            ["ky"] = "KY",
            ["lv"] = "LV",
            ["lt"] = "LT",
            ["mk"] = "MK",
            ["ms"] = "MS",
            ["ml"] = "ML",
            ["mni"] = "MNI",
            ["mn"] = "MN",
            ["no"] = "NO",
            ["pl"] = "PL",
            ["pt"] = "PT",
            ["pt-BR"] = "BR_PT",
            ["ro"] = "RO",
            ["ru"] = "RU",
            ["sr"] = "SR",
            ["sr-Cyrl"] = "SR_CYRL",
            ["si"] = "SI",
            ["sk"] = "SK",
            ["sl"] = "SL",
            ["es"] = "ES",
            ["su"] = "SU",
            ["sv"] = "SV",
            ["tl"] = "TL",
            ["ta"] = "TA",
            ["te"] = "TE",
            ["th"] = "TH",
            ["tr"] = "TR",
            ["uk"] = "UK",
            ["ur"] = "UR",
            ["vi"] = "VI",
        };
}
